### ISSUE TITLE
I need help！

### ISSUE THREAD

**Issue by RoiSoleil520** [zanseven007/generator-zyy-h5#5]
module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Vue\my-first-h5\node_modules\._gulp@3.9.1@gulp\bin                         \gulp.js:4:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\                         node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Zanyuyu@2.1.4 dev: `gulp dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Zanyuyu@2.1.4 dev script 'gulp dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Zanyuyu package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Zanyuyu
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Zanyuyu
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Vue\my-first-h5\npm-debug.log

**Comment by zanseven007** [comment]
fixed[#247c13](https://github.com/zanseven007/generator-zyy-h5/commit/247c13db0ddb4e383030616721f417040c3e2d30)
